// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAJQF9iD3nrp26P1ZWxiL_qbmYVIArOoI',
    appId: '1:1010508455383:web:ec1703d2b07d3a298d7f92',
    messagingSenderId: '1010508455383',
    projectId: 'dummy-6d6a3',
    authDomain: 'dummy-6d6a3.firebaseapp.com',
    storageBucket: 'dummy-6d6a3.firebasestorage.app',
    databaseURL: "https://dummy-6d6a3-default-rtdb.firebaseio.com/",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1zau8MkdUEaPu7ye5rQV_zKXdXxPkVDU',
    appId: '1:1010508455383:android:224392ac2600be5d8d7f92',
    messagingSenderId: '1010508455383',
    projectId: 'dummy-6d6a3',
    storageBucket: 'dummy-6d6a3.firebasestorage.app',
    databaseURL: "https://dummy-6d6a3-default-rtdb.firebaseio.com/",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJuWXPHv1S9Q0mwvcz-pAMgIMGvv_xb2E',
    appId: '1:1010508455383:ios:03c7a25b304602a58d7f92',
    messagingSenderId: '1010508455383',
    projectId: 'dummy-6d6a3',
    storageBucket: 'dummy-6d6a3.firebasestorage.app',
    iosBundleId: 'com.example.dummy',
    databaseURL: "https://dummy-6d6a3-default-rtdb.firebaseio.com/",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJuWXPHv1S9Q0mwvcz-pAMgIMGvv_xb2E',
    appId: '1:1010508455383:ios:03c7a25b304602a58d7f92',
    messagingSenderId: '1010508455383',
    projectId: 'dummy-6d6a3',
    storageBucket: 'dummy-6d6a3.firebasestorage.app',
    iosBundleId: 'com.example.dummy',
    databaseURL: "https://dummy-6d6a3-default-rtdb.firebaseio.com/",
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAJQF9iD3nrp26P1ZWxiL_qbmYVIArOoI',
    appId: '1:1010508455383:web:ac85a90a9ad7ce9c8d7f92',
    messagingSenderId: '1010508455383',
    projectId: 'dummy-6d6a3',
    authDomain: 'dummy-6d6a3.firebaseapp.com',
    storageBucket: 'dummy-6d6a3.firebasestorage.app',
    databaseURL: "https://dummy-6d6a3-default-rtdb.firebaseio.com/",
  );
}
